version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: noud 
      POSTGRES_PASSWORD: test1234 
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 1000:8080

